stages:
- test
- publish
- deploy

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

variables:
  POSTGRES_DB: gestalt-meta
  POSTGRES_USER: gestaltdev
  POSTGRES_PASSWORD: letmein
  DATABASE_HOSTNAME: postgres
  DATABASE_NAME: gestalt-meta
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: gestaltdev
  DATABASE_PASSWORD: letmein
  DATABASE_TIMEOUT_MS: 5000
  ROOT_USERNAME: root
  ROOT_PASSWORD: letmein
  DOCKER_IMG: "galacticfog/gestalt-meta"
  GESTALT_SECURITY_PROTOCOL: http
  GESTALT_SECURITY_HOSTNAME: galacticfog__gestalt-security
  GESTALT_SECURITY_PORT: 80
  GESTALT_SECURITY_KEY: missing
  GESTALT_SECURITY_SECRET: missing
  GESTALT_APIGATEWAY: "http://no-gateway"
  GESTALT_LAMBDA: "http://no-lambda"
  RABBIT_HOST: no-rabbit
  RABBIT_PORT: 5672
  RABBIT_HTTP_PORT: 15672
  RABBIT_EXCHANGE: policy
  RABBIT_ROUTE: test-route

test:
  stage: test
  services:
    #no database or security integration tests yet
    #- postgres:9.4
    #- galacticfog/gestalt-security:2.2.5-SNAPSHOT-b246c46b
  script:
    - sbt clean update test docker:stage

publish-branch:
  stage: publish
  script: 
    - VERSION=$(grep "^version" build.sbt | sed 's/.*:=[ ]*//' | sed 's/"//g')
    - DOCKER_TAG=$VERSION-${CI_BUILD_REF:0:8}
    - cd target/docker/stage
    - docker build -t $DOCKER_IMG:$DOCKER_TAG .
    - docker push     $DOCKER_IMG:$DOCKER_TAG
  only:
    - master
    - /^release-.*$/
  except:
    - tags

publish-tag: 
  stage: publish
  script:
    - cd target/docker/stage
    - docker build -t $DOCKER_IMG:$CI_BUILD_TAG .
    - docker push     $DOCKER_IMG:$CI_BUILD_TAG
  only:
    - tags

.github-publish:
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://$GITHUB_CREDENTIALS@github.com/GalacticFog/gestalt-meta.git
    - |
      if [ -z ${CI_BUILD_TAG} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push github $CI_BUILD_TAG
      fi
  only:
    - master
    - /^release-.*$/
    - tags

deploy-to-test:
  stage: deploy
  environment: test
  script: 
    - echo checking for access to marathon
    - curl http://marathon.mesos:8080/v2/apps/gestalt-test/meta || true
